FROM ghcr.io/puppeteer/puppeteer:23.5.3@sha256:ed20831e147f6c277d436946cc0f0088f47900906ca7a798816236fe60f37347

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

RUN apt-get update && \
  # Install ImageMagick build dependencies.
  # TODO: lock_versions to ensure deterministic behaviour.
  apt-get install -y autoconf pkg-config build-essential libpng-dev && \
  apt-get clean && \
  apt-get autoremove && \
  rm -rf /var/lib/apt/lists/* && \
  # Build ImageMagick from source.
  # ImageMagick is used as a HTML image diff tool.
  curl "https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.1-39.tar.gz" -L -o /tmp/ImageMagick.tar.gz && \
  tar xzf /tmp/ImageMagick.tar.gz --directory /tmp && \
  mkdir -p /tmp/ImageMagick && \
  cd /tmp/ImageMagick && \
  sh /tmp/ImageMagick-7.1.1-39/configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-jpeg=yes --with-jp2=yes --with-png=yes --with-tiff=yes --with-xml=yes --with-gs-font-dir=yes && \
  make -j && \
  make install && \
  ldconfig /usr/local/lib/ && \
  rm -rf /tmp/* && \
  # Symlink the pptruser user puppeteer cache folder to the node user home folder.
  # Required for the javascript puppeteer library to be able to find the browser binary when being run by the node user.
  ln -s /home/pptruser/.cache /home/node/.cache

USER node

WORKDIR /opt/app

# Allow the already installed npm puppeteer npm modules to be loaded from anywhere / by any user.
ENV NODE_PATH=/home/pptruser/node_modules/:/usr/local/lib/node_modules/

# Watch the `./generated/cv.html` file for changes and calculate the image difference from the deployed `https://cv.nunorodrigues.tech/` version of the CV.
CMD [ "make", "watch-html-and-diff" ]
