FROM ghcr.io/puppeteer/puppeteer:23.5.3@sha256:ed20831e147f6c277d436946cc0f0088f47900906ca7a798816236fe60f37347

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /opt/app

USER root

RUN apt-get update && \
  # Install ImageMagick build dependencies.
  # TODO: lock_versions to ensure deterministic behaviour.
  apt-get install -y autoconf pkg-config build-essential libpng-dev && \
  apt-get clean && \
  apt-get autoremove && \
  rm -rf /var/lib/apt/lists/* && \
  # Build ImageMagick from source.
  # ImageMagick is used as a HTML image diff tool.
  curl "https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.1-39.tar.gz" -L -o /tmp/ImageMagick.tar.gz && \
  tar xzf /tmp/ImageMagick.tar.gz --directory /tmp && \
  mkdir -p /tmp/ImageMagick && \
  cd /tmp/ImageMagick && \
  sh /tmp/ImageMagick-7.1.1-39/configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-jpeg=yes --with-jp2=yes --with-png=yes --with-tiff=yes --with-xml=yes --with-gs-font-dir=yes && \
  make -j && \
  make install && \
  ldconfig /usr/local/lib/ && \
  rm -rf /tmp/*

USER node

# docker build -f ./Dockerfile.diff -t tttt .
# docker run -it -v "${PWD}/tmp:/opt/app" tttt bash
# curl https://www.bannerbear.com/images/ghost/2023-01-04-how-to-compare-puppeteer-screenshots-using-imagemagick/0.png -o ./1.png
# curl https://www.bannerbear.com/images/ghost/2023-01-04-how-to-compare-puppeteer-screenshots-using-imagemagick/1.png -o ./2.png
# magick compare 1.png 2.png difference.png
# curl -L https://user-images.githubusercontent.com/13458218/135765002-e67e67bd-82c2-4a2f-920d-3f4f8f42ba28.jpg -o 3.jpg
# curl -L https://user-images.githubusercontent.com/13458218/135765013-2f94bb1a-9b9f-4528-883d-d279306382be.jpg -o 4.jpg
# magick compare -fuzz 1% 3.jpg 4.jpg difference3.jpg
