version: "3"
services:
  deno-dev-container:
    container_name: deno-dev-container
    build:
      dockerfile: ./Dockerfile
      context: .
      target: dev-container
    volumes:
      - .:/opt/app
  html-diff:
    container_name: html-diff
    build:
      dockerfile: ./Dockerfile.diff
      context: .
    volumes:
      - .:/opt/app
