version: "3"
services:
  deno-dev-container:
    container_name: deno-dev-container
    build:
      dockerfile: ./Dockerfile
      context: .
      target: dev-container
    # Reap zombie processes (mainly from chrome).
    init: true
    volumes:
      - .:/opt/app
