name: CD

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  DOCKER_BUILDKIT: 1
  USE_CONTAINER_CACHE: true
  CI_CONTAINER_IMAGE_NAME: ghcr.io/nmfr/cv/ci

jobs:
  cache-ci-container-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: (echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin)
      - name: docker build
        run: make container run="echo 'image built'"
      - name: docker push
        run: docker push $CI_CONTAINER_IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    needs: cache-ci-container-image
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: (echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin) || true
      - name: spell check
        run: make container run="make clean spell-check"
      - name: prepare gh-pages folder
        run: make prepare-gh-pages
      - name: Deploy github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
