name: CD

on:
  push:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1
  CI_CONTAINER_IMAGE_NAME: docker.pkg.github.com/nmfr/cv/ci

jobs:
  pus-ci-container-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: make ci-container-build
      - run: make ci-container-push
