name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spell-check:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: nmfr/cv/ci
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/$DOCKER_IMAGE_NAME || true
      - run: make ci-spell-check
      - run: docker push docker.pkg.github.com/$DOCKER_IMAGE_NAME || true
