name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spell-check:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: $GITHUB_REPOSITORY/ci
    steps:
      - uses: actions/checkout@v2
      - run: echo ${DOCKER_IMAGE_NAME}
