name: CI

on:
  pull_request:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1
  CI_CONTAINER_IMAGE_NAME: docker.pkg.github.com/nmfr/cv/ci

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: make ci-container-build
      - run: make ci-spell-check
