name: CI

on:
  pull_request:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1
  USE_CONTAINER_CACHE: true
  CI_CONTAINER_IMAGE_NAME: ghcr.io/nmfr/cv/ci

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: (echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin) || true
      - run: make container run="make clean spell-check"
      - name: docker push
        run: docker push $CI_CONTAINER_IMAGE_NAME
