name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make ci-spell-check
